checks:
    php:
        code_rating: true
        variable_existence: true
        useless_calls: true
        use_statement_alias_conflict: true
        unused_variables: true
        unused_properties: true
        unused_parameters: true
        unused_methods: true
        unreachable_code: true
        sql_injection_vulnerabilities: true
        security_vulnerabilities: true
        precedence_mistakes: true
        precedence_in_conditions: true
        parameter_non_unique: true
        no_property_on_interface: true
        no_non_implemented_abstract_methods: true
        deprecated_code_usage: true
        closure_use_not_conflicting: true
        closure_use_modifiable: true
        avoid_useless_overridden_methods: true
        avoid_conflicting_incrementers: true
        assignment_of_null_return: true
        uppercase_constants: true
        too_many_arguments: true
        verify_property_names: true
        verify_access_scope_valid: true
        missing_arguments: true
        prefer_sapi_constant: true
        no_unnecessary_function_call_in_for_loop: true
        remove_php_closing_tag: true
        fix_php_opening_tag: true
        fix_doc_comments: true
        verify_argument_usable_as_reference: true
        use_self_instead_of_fqcn: true
        switch_fallthrough_commented: true
        return_doc_comments: true
        return_doc_comment_if_not_inferrable: true
        parameter_doc_comments: true
        no_eval: true
        fix_linefeed: true
        fix_line_ending: true
        fix_identation_4spaces: true
        ensure_lower_case_builtin_functions: true
        avoid_tab_indentation: true
        method_calls_on_non_object: true
        argument_type_checks: true
        param_doc_comment_if_not_inferrable: true
        no_unnecessary_if: true
        no_empty_statements: true
        avoid_corrupting_byteorder_marks: true
        no_global_keyword: false
        avoid_superglobals: false
        one_class_per_file: false
        no_commented_out_code: false
        side_effects_or_types: false
        no_exit: false

filter:
    paths:
        - 'src/htdocs/wp-content/plugins/titanium*'

    excluded_paths:
        - 'tests/'
        - 'wp-content/themes/*'

tools:
    php_sim: true
    php_pdepend: true
    php_analyzer:
        dependency_paths:
            - wp-content/wp-admin/
            - wp-content/wp-includes/
    php_code_sniffer: true
    php_loc: true
    js_hint:
        use_native_config: false
        config:
            "laxbreak": true
